"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

const faqData = [
    {
        question: "How accurate is VerifyAI?",
        answer:
            "VerifyAI provides confidence scores and advanced AI detection algorithms with up to 98% accuracy in demo testing.",
    },
    {
        question: "Can VerifyAI detect AI generated video?",
        answer:
            "Yes. VerifyAI is able to detect AI generated video. This feature is coming soon.",
    },
    {
        question: "Can it detect ChatGPT, Gemini and Claude content?",
        answer:
            "Yes. VerifyAI can analyze content generated by multiple AI models including ChatGPT, Gemini and Claude.",
    },
    {
        question: "What file formats are supported?",
        answer:
            "Currently JPG, JPEG, PNG and WEBP are supported. Video support is coming soon.",
    },
    {
        question: "Is there a free plan?",
        answer:
            "Yes. Every user gets 10 free analyses per day in the demo version.",
    },
    {
        question: "Do I need an account?",
        answer:
            "You can explore the website without an account, but analysis and history features require registration.",
    },
];

export default function FAQ() {
    const [user, setUser] = useState<any>(null);

    useEffect(() => {
        async function getUser() {
            const {
                data: { user },
            } = await supabase.auth.getUser();

            setUser(user);
        }

        getUser();
    }, []);
    const [open, setOpen] = useState<number | null>(null);

    return (
        <section
            id="faq"
            className="max-w-5xl mx-auto px-6 py-24"
        >
            <div className="text-center mb-16">

                <span className="px-4 py-2 rounded-full bg-purple-500/20 text-purple-300 text-sm border border-purple-500/20">
                    FAQ
                </span>

                <h2 className="text-5xl font-bold mt-6">
                    Frequently Asked Questions
                </h2>

                <p className="text-white/60 mt-4">
                    Everything you need to know about VerifyAI.
                </p>

            </div>

            <div className="space-y-4">

                {faqData.map((item, index) => (
                    <div
                        key={index}
                        className="
              border
              border-white/10
              rounded-2xl
              bg-white/[0.03]
              overflow-hidden
            "
                    >
                        <button
                            onClick={() =>
                                setOpen(open === index ? null : index)
                            }
                            className="
                w-full
                flex
                justify-between
                items-center
                p-6
                text-left
                hover:bg-white/[0.02]
                transition
              "
                        >
                            <span className="font-medium text-lg">
                                {item.question}
                            </span>

                            <span className="text-2xl text-purple-400">
                                {open === index ? "−" : "+"}
                            </span>
                        </button>

                        {open === index && (
                            <div className="px-6 pb-6 text-white/60 leading-relaxed">
                                {item.answer}
                            </div>
                        )}

                    </div>
                ))}

            </div>

            <div className="text-center mt-12">

                <a
                    href={user ? "/dashboard" : "/signup"}
                    className="
    inline-block
    px-8
    py-4
    rounded-xl
    bg-gradient-to-r
    from-blue-500
    to-purple-600
    hover:scale-105
    transition
    "
                >
                    {user ? "My Dashboard" : "Get Started Free"}
                </a>

            </div>

        </section>
    );
}